# Generated by Django 3.1.3 on 2021-01-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210119_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_created',
        ),
    ]
