# Generated by Django 3.1.3 on 2021-01-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_myuser_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
